version: "3.2"

services:
  latex:
    image: 'docker.pkg.github.com/peaceiris/docker-latex/latex:v1.1.0-full'
    build:
      context: .
      cache_from:
        - 'docker.pkg.github.com/peaceiris/docker-latex/latex:v1.1.0-full'
    container_name: 'latex_v1.1.0'
    volumes:
      - ${PWD}:/work
    stdin_open: true
    tty: true
    working_dir: /work
    command: latexmk -pdf -pvc
