name: Docker CI/CD

on:
  push:
    branches:
      - main
    paths:
      - '.dockerignore'
      - '.github/**'
      - '.hadolint.yaml'
      - 'Dockerfile'
      - 'ieee-template/**'
  pull_request:
    paths:
      - '.dockerignore'
      - '.github/**'
      - '.hadolint.yaml'
      - 'Dockerfile'
      - 'ieee-template/**'

jobs:
  hadolint:
    runs-on: ubuntu-18.04
    container:
      image: 'hadolint/hadolint:v1.20.0-alpine'
    steps:
      - uses: actions/checkout@v2
      - run: hadolint ./Dockerfile

  push:
    runs-on: ubuntu-18.04
    needs: hadolint
    steps:
      - uses: actions/checkout@v2
      - name: Login to Packages
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login 'docker.pkg.github.com' -u 'peaceiris' --password-stdin
      # - run: docker-compose pull --quiet
      #   if: github.event_name == 'pull_request'
      - run: docker-compose build
      - run: docker images
      - name: latexmk -pdf
        run: docker-compose run --rm -T latex latexmk -pdf
      - run: docker-compose push
        if: github.ref == 'refs/heads/main'
